# Generated by Django 6.0.1 on 2026-01-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('treinador', models.CharField(max_length=100)),
                ('ano_fundacao', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('epoca', models.CharField(max_length=9)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('golos_casa', models.PositiveIntegerField(default=0)),
                ('golos_fora', models.PositiveIntegerField(default=0)),
                ('equipa_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='liga_api.equipa')),
                ('equipa_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='liga_api.equipa')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='liga_api.liga')),
            ],
        ),
        migrations.AddField(
            model_name='equipa',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipas', to='liga_api.liga'),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(choices=[('GR', 'Guarda-Redes'), ('DEF', 'Defesa'), ('MED', 'Médio'), ('AV', 'Avançado')], max_length=3)),
                ('numero', models.PositiveIntegerField()),
                ('idade', models.PositiveIntegerField()),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='liga_api.equipa')),
            ],
            options={
                'unique_together': {('equipa', 'numero')},
            },
        ),
    ]
